package dev.jausc.myflix.core.common.potoken

import android.content.Context
import java.io.Closeable

/**
 * Interface for generating poTokens for YouTube video playback.
 * Implementations can use different methods (e.g., WebView-based BotGuard).
 */
interface PoTokenGenerator : Closeable {
    /**
     * Generates a poToken for the provided identifier, using the integrityToken and
     * webPoSignalOutput previously obtained during initialization.
     * Can be called multiple times for different video IDs.
     *
     * @param identifier The video ID or visitor data to generate a token for
     * @return The generated poToken as a base64-encoded string
     */
    suspend fun generatePoToken(identifier: String): String

    /**
     * @return Whether the integrity token is expired, in which case all tokens
     * generated by [generatePoToken] will be invalid
     */
    fun isExpired(): Boolean

    /**
     * Factory interface for creating PoTokenGenerator instances.
     */
    interface Factory {
        /**
         * Initializes a [PoTokenGenerator] by loading the BotGuard VM, running it,
         * and obtaining an integrity token. Can then be used multiple times to
         * generate poTokens with [generatePoToken].
         *
         * @param context Used to load assets and instantiate WebView
         * @return An initialized PoTokenGenerator
         */
        suspend fun newPoTokenGenerator(context: Context): PoTokenGenerator
    }
}
